/*
** Jeu de données projet
*/

/* Dropping existing tables */
DROP TABLE IF EXISTS CITOYEN;
DROP TABLE IF EXISTS JUSTIFICATIF;
DROP TABLE IF EXISTS DEMANDE; 
DROP TABLE IF EXISTS DEPARTEMENT; 
DROP TABLE IF EXISTS REGION; 
DROP TABLE IF EXISTS COMMUNE;
DROP TABLE IF EXISTS SERVICE;
DROP TABLE IF EXISTS UNION_CIVILE;
DROP TABLE IF EXISTS ELECTION;
DROP TABLE IF EXISTS ETAT_CIVIL;
DROP TABLE IF EXISTS RESTAURATION;
DROP TABLE IF EXISTS SCOLAIRE;
DROP TABLE IF EXISTS SIGNALEMENT;
DROP TABLE IF EXISTS ENFANT;
DROP TABLE IF EXISTS CANTINE;
DROP TABLE IF EXISTS ECOLE;
DROP TABLE IF EXISTS LIEU;
DROP TABLE IF EXISTS MANGE;
DROP TABLE IF EXISTS SCOLARISE;

/* Creating tables */ 

CREATE TABLE REGION ( code_INSEER INT, nomR VARCHAR(50), PRIMARY KEY(code_INSEER));
CREATE TABLE DEPARTEMENT ( code_INSEED INT, nomD VARCHAR(50), code_INSEER INT REFERENCES REGION(code_INSEER), PRIMARY KEY(code_INSEED));
CREATE TABLE COMMUNE ( idC INT, CodePostal INT, nomC VARCHAR(50), coordonnees VARCHAR(50), code_INSEEC INT, adresseMairie VARCHAR(50), code_INSEED INT REFERENCES DEPARTEMENT(code_INSEED), PRIMARY KEY (idC));
CREATE TABLE SERVICE ( libelle VARCHAR(250), descriptionS VARCHAR(250), periodOuverture VARCHAR(50), tarif VARCHAR(250), idC INT REFERENCES COMMUNE(idC), PRIMARY KEY(libelle));
CREATE TABLE DEMANDE ( idD INT, dateD DATE, message VARCHAR(250), libelle VARCHAR(100) REFERENCES SERVICE(libelle), nomCI VARCHAR(50) REFERENCES CITOYEN(nomCI), prenomCI VARCHAR(50) REFERENCES CITOYEN(prenomCI), dateNaissance DATE REFERENCES CITOYEN(dateNaissance), PRIMARY KEY(idD)); 
CREATE TABLE JUSTFICATIF ( numeroJ INT, idD INT REFERENCES DEMANDE(idD), typeJ VARCHAR(50), descriptionJ VARCHAR(250), cheminFichier VARCHAR(500), PRIMARY KEY(numeroJ, idD));
CREATE TABLE CITOYEN ( nomCI VARCHAR(50), prenomCI VARCHAR(50), dateNaissance DATE, adresseCI VARCHAR(250), telCI VARCHAR(12), mailCI VARCHAR(250), idUNIS INT REFERENCES UNIS(idUNIS), PRIMARY KEY(nomCI, prenomCI, dateNaissance));
CREATE TABLE UNION_CIVILE ( libelle VARCHAR(250), dateU DATE, typeU VARCHAR(100), PRIMARY KEY(libelle, dateU, typeU));
CREATE TABLE ELECTION ( libelle VARCHAR(250), bureauDeVote VARCHAR(100), PRIMARY KEY(libelle, bureauDeVote));
CREATE TABLE ETAT_CIVIL ( libelle VARCHAR(250), typeDocument VARCHAR(100), dateDispo DATE, PRIMARY KEY(libelle, typeDocument, dateDispo));
CREATE TABLE SIGNALEMENT ( libelle VARCHAR(250), typeSI VARCHAR(100), idL INT REFERENCES LIEU(idL), PRIMARY KEY(libelle, typeSI));
CREATE TABLE SCOLAIRE ( libelle VARCHAR(250), nomS VARCHAR(250), numeroS VARCHAR(12), nomE VARCHAR(50) REFERENCES ENFANT(nomE), prenomE VARCHAR(50) REFERENCES ENFANT(prenomE), PRIMARY KEY(libelle, nomS, numeroS));
CREATE TABLE RESTAURATION ( libelle VARCHAR(250), quotientFamilial INT, nomE VARCHAR(50) REFERENCES ENFANT(nomE), prenomE VARCHAR(50) REFERENCES ENFANT(prenomE), PRIMARY KEY(libelle, quotientFamilial));
CREATE TABLE ENFANT ( nomE VARCHAR(50), prenomE VARCHAR(50), adresseCA VARCHAR(250) REFERENCES CANTINE(adresseCA), adresseEC VARCHAR(250) REFERENCES ECOLE(adresseEC), PRIMARY KEY(nomE, prenomE));
CREATE TABLE MANGE ( adresseCA VARCHAR(250) REFERENCES CANTINE(adresseCA), nomE VARCHAR(50) REFERENCES ENFANT(nomE), prenomE VARCHAR(50) REFERENCES ENFANT(prenomE), dateDebut DATE, dateFin DATE, nbAbs INT, PRIMARY KEY(adresseCA, nomE, prenomE));
CREATE TABLE SCOLARISE ( adresseEC VARCHAR(250) REFERENCES ECOLE(adresseEC), nomE VARCHAR(50) REFERENCES ENFANT(nomE), prenomE VARCHAR(50) REFERENCES ENFANT(prenomE), classe VARCHAR(5), premIA VARCHAR(5), PRIMARY KEY(adresseEC, nomE, prenomE));
CREATE TABLE CANTINE ( adresseCA VARCHAR(250), nomCA VARCHAR(100), nbPlace INT, nbService INT, latCA FLOAT, longCA FLOAT, idL INT REFERENCES LIEU(idL), PRIMARY KEY(adresseCA, nomCA));
CREATE TABLE ECOLE ( adresseEC VARCHAR(250), nbClasse INT, idL INT REFERENCES LIEU(idL), PRIMARY KEY(adresseEC));
CREATE TABLE LIEU ( idL INT, nomL VARCHAR(50), typeL VARCHAR(100), latL FLOAT, longL FLOAT, PRIMARY KEY(idL));

